{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "talos-cluster-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "talos-cluster-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "talos-cluster-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.service.port }}
      targetPort: proxy
      protocol: TCP
{{- end }}
